# Generated by Django 2.2.7 on 2019-11-17 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='ej. Juan', max_length=50)),
                ('correo', models.CharField(help_text='ej. juanperez@gmail.com', max_length=50)),
                ('fono', models.CharField(help_text='ej. 998765432', max_length=50)),
                ('motivo', models.CharField(max_length=50)),
                ('comentario', models.CharField(max_length=500)),
            ],
        ),
    ]
