# Generated by Django 2.2.7 on 2019-11-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimePlus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='motivo',
            field=models.CharField(help_text='Solo una frase', max_length=50),
        ),
    ]
